/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import org.gradle.api.tasks.testing.Test
import org.gradle.plugins.ide.idea.model.IdeaLanguageLevel

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "2.2.0"
    
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Apply the idea plugin to generate IDEA project files.
    idea

    id("org.jetbrains.kotlin.plugin.serialization") version "2.2.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Configure JUnit Platform for all test tasks
tasks.withType<Test> {
    useJUnitPlatform()
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    // Define the main class for the application.
    mainClass = "gen.ai.AppKt"
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.1")
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.2.0")

    // SLF4J + Logback for logging
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("ch.qos.logback:logback-classic:1.2.11")

    // Kotest framework
    testImplementation("io.kotest:kotest-runner-junit5-jvm:5.9.1")
    testImplementation("io.kotest:kotest-assertions-core-jvm:5.9.1")
}
